# Generated by Django 3.2.8 on 2021-11-05 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211105_1115'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='caegory',
            new_name='category',
        ),
    ]
