# Generated by Django 3.2.8 on 2021-11-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_caegory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='deliveredAt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
