# Generated by Django 3.2.8 on 2021-11-06 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_review_deliveredat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='deliveredAt',
        ),
        migrations.AddField(
            model_name='review',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
